### ISSUE TITLE
[read-fonts] map_codepoint panics on BIZUDPMincho-Regular.ttf

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#797]
In walking across https://github.com/google/fonts for https://github.com/rsheeter/find_dups I discovered that we have fonts that make map_codepoint kerplode. If you clone google/fonts as sibling to fontations https://github.com/googlefonts/fontations/compare/main...kerplode should reproduce the problem.

```shell
$ cargo test -p read-fonts bizudp
    Blocking waiting for file lock on build directory
   Compiling read-fonts v0.15.5 (/usr/local/google/home/rsheeter/oss/fontations/read-fonts)
    Finished test [unoptimized + debuginfo] target(s) in 4.73s
     Running unittests src/lib.rs (target/debug/deps/read_fonts-4ccee56fc0ffcb82)

running 1 test
test table_provider::tests::bizudpmincho_style_cmap ... FAILED

failures:

---- table_provider::tests::bizudpmincho_style_cmap stdout ----
thread 'table_provider::tests::bizudpmincho_style_cmap' panicked at read-fonts/src/tables/../../generated/generated_cmap.rs:745:37:
called `Result::unwrap()` on an `Err` value: InvalidArrayLen
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: read_fonts::tables::cmap::<impl read_fonts::table_ref::TableRef<read_fonts::tables::cmap::Cmap4Marker>>::glyph_id_array
             at ./src/tables/../../generated/generated_cmap.rs:745:9
   5: read_fonts::tables::cmap::<impl read_fonts::table_ref::TableRef<read_fonts::tables::cmap::Cmap4Marker>>::lookup_glyph_id
             at ./src/tables/cmap.rs:87:19
   6: read_fonts::tables::cmap::<impl read_fonts::table_ref::TableRef<read_fonts::tables::cmap::Cmap4Marker>>::map_codepoint
             at ./src/tables/cmap.rs:62:24
   7: read_fonts::tables::cmap::<impl read_fonts::table_ref::TableRef<read_fonts::tables::cmap::CmapMarker>>::map_codepoint
             at ./src/tables/cmap.rs:30:55
   8: read_fonts::table_provider::tests::bizudpmincho_style_cmap
             at ./src/table_provider.rs:231:9
   9: read_fonts::table_provider::tests::bizudpmincho_style_cmap::{{closure}}
             at ./src/table_provider.rs:225:33
  10: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
```

**Comment by dfrg** [comment]
Haven’t looked at the actual font yet but it looks like this is a weird interaction with `count(..)` on an array with an element type of size > 1. We don’t ensure that the length of the remaining bytes is a multiple of element size and `read_array` fails here: https://github.com/googlefonts/fontations/blob/130fc7ac18f53aaf8fa2b9209d430977a9931aba/read-fonts/src/font_data.rs#L173

That check doesn’t seem to be strictly necessary so we could just remove it. Alternatively, we change codegen so that count considers element size.
