### ISSUE TITLE
Panic in sbix header parsing due to overflow when computing end of strikes array

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#959]
Spun off from [crbug.com/347835680](https://crbug.com/347835680):

https://clusterfuzz.com/testcase-detail/5420281400066048 has more details:

Relevant stack context:

```
#16 0xf2397321 in core::panicking::panic_fmt::h2dc742118ebea367 [third_party/rust-toolchain/lib/rustlib/src/rust/library/core/src/panicking.rs:72](https://chromium.googlesource.com/chromium/src/+/2055f9b7d19a9b1d2342eb5818b80d3fab334169/third_party/rust-toolchain/lib/rustlib/src/rust/library/core/src/panicking.rs#72):14
    #17 0xf2364317 in core::panicking::panic_const::panic_const_mul_overflow::h11989d665f9cc022 [third_party/rust-toolchain/lib/rustlib/src/rust/library/core/src/panicking.rs:179](https://chromium.googlesource.com/chromium/src/+/2055f9b7d19a9b1d2342eb5818b80d3fab334169/third_party/rust-toolchain/lib/rustlib/src/rust/library/core/src/panicking.rs#179):21
    #18 0xee6415f2 in read_fonts::tables::sbix::_$LT$impl$u20$read_fonts..read..FontReadWithArgs$u20$for$u20$read_fonts..table_ref..TableRef$LT$read_fonts..tables..sbix..SbixMarker$GT$$GT$::read_with_args::h41422c524b7432b0 [third_party/rust/chromium_crates_io/vendor/read-fonts-0.19.3/generated/generated_sbix.rs:359](https://chromium.googlesource.com/chromium/src/+/2055f9b7d19a9b1d2342eb5818b80d3fab334169/third_party/rust/chromium_crates_io/vendor/read-fonts-0.19.3/generated/generated_sbix.rs#359):39
    #19 0xee64170d in read_fonts::tables::sbix::_$LT$impl$u20$read_fonts..table_ref..TableRef$LT$read_fonts..tables..sbix..SbixMarker$GT$$GT$::read::hd98b1281c207fad4 [third_party/rust/chromium_crates_io/vendor/read-fonts-0.19.3/generated/generated_sbix.rs:375](https://chromium.googlesource.com/chromium/src/+/2055f9b7d19a9b1d2342eb5818b80d3fab334169/third_party/rust/chromium_crates_io/vendor/read-fonts-0.19.3/generated/generated_sbix.rs#375):9
    #20 0xee4d5618 in read_fonts::table_provider::TableProvider::sbix::h5a74189d0aa1cb60 [third_party/rust/chromium_crates_io/vendor/read-fonts-0.19.3/src/table_provider.rs:165](https://chromium.googlesource.com/chromium/src/+/2055f9b7d19a9b1d2342eb5818b80d3fab334169/third_party/rust/chromium_crates_io/vendor/read-fonts-0.19.3/src/table_provider.rs#165):9
```

And the bits of generated code here look like this:

```
impl<'a> FontReadWithArgs<'a> for Sbix<'a> {
    fn read_with_args(data: FontData<'a>, args: &u16) -> Result<Self, ReadError> {
        let num_glyphs = *args;
        let mut cursor = data.cursor();
        cursor.advance::<u16>();
        cursor.advance::<HeaderFlags>();
        let num_strikes: u32 = cursor.read()?;
        ➡️ let strike_offsets_byte_len = num_strikes as usize * Offset32::RAW_BYTE_LEN;
        cursor.advance_by(strike_offsets_byte_len);
        cursor.finish(SbixMarker {
            num_glyphs,
            strike_offsets_byte_len,
        })
    }
}
```

So  `num_strikes as usize * Offset32::RAW_BYTE_LEN;` overflows and is only then passed to `advance_by()` - which has a range check for whether we stay inside the sbix table. 

I see two ways of fixing this. Using `saturating_mul` here in which case the `cursor.advance_by()` would catch the out of bounds cursor, or adding an `advance_by_n_times()` function or something like that which would then catch this as well?

**Comment by drott** [comment]
Or again `wrapped_mul()`, but also, looking closer, I wonder why it could ever panic with __attempt to multiply with overflow__ there if `num_strikes` is `u32` and the mutiplier is 4, and the result type is `usize`.

**Comment by drott** [comment]
Might be that the [x86_libfuzzer_chrome_asan](https://clusterfuzz.com/testcases?job=x86_libfuzzer_chrome_asan) configuration is indeed 32bit...

**Comment by drott** [comment]
Yes, reproducible with a test with the test fonts from the fuzzer failure and 
`cargo test --target=i686-unknown-linux-gnu "sbix_strikes_count_overflow"`
